repos:

  # Checkov
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.245
    hooks:
      - id: checkov
        name: checkov
        description: "Static code analysis for security and compliance"
        files: .+
        verbose: false

  # Pip Audit
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
    - id: pip-audit
      name: pip-audit
      description: "Audits Python environments and dependency trees for known vulnerabilities"
      entry: pip-audit
      pass_filenames: false
      language: python

  # Generic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        name: fix end of files
        description: "Ensures that a file is either empty, or ends with one newline"
        entry: end-of-file-fixer
        stages: [ commit, push, manual ]
        types: [ text ]
        language: python

      - id: trailing-whitespace
        name: trim trailing whitespace
        description: "Trims trailing whitespace"
        entry: trailing-whitespace-fixer
        types: [ text ]
        language: python
        stages: [ commit ]

  # YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        name: check yaml
        description: "Checks .yaml files for parseable syntax"
        entry: check-yaml
        types: [ yaml ]
        language: python

  # YAPF
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        name: yapf
        description: "A formatter for Python files"
        entry: yapf
        args: [ -i ] # inplace
        language: python
        types: [ python ]
        additional_dependencies: [ toml ]
